// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  {
    slug: "pogrebenie",
    name: "\u041F\u043E\u0433\u0440\u0435\u0431\u0435\u043D\u0438\u0435",
    url: "https://kiparisbg.com/pogrebenie",
    description: "\u041F\u044A\u043B\u043D\u0430 \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044F \u043D\u0430 \u0434\u043E\u0441\u0442\u043E\u0439\u043D\u043E \u043F\u043E\u0433\u0440\u0435\u0431\u0435\u043D\u0438\u0435 \u0432 \u0421\u043E\u0444\u0438\u044F \u2014 \u0442\u0440\u0430\u043D\u0441\u043F\u043E\u0440\u0442, \u043A\u043E\u0432\u0447\u0435\u0433, \u0440\u0438\u0442\u0443\u0430\u043B, \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044F."
  },
  {
    slug: "kremacia",
    name: "\u041A\u0440\u0435\u043C\u0430\u0446\u0438\u044F",
    url: "https://kiparisbg.com/kremacia",
    description: "\u041A\u0440\u0435\u043C\u0430\u0446\u0438\u044F \u0432 \u0421\u043E\u0444\u0438\u044F \u0441 \u043F\u044A\u043B\u043D\u043E \u0441\u044A\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043F\u043E \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0438 \u0438 \u0443\u0440\u043D\u0430."
  },
  {
    slug: "prevoz-na-pokoinik",
    name: "\u041F\u0440\u0435\u0432\u043E\u0437 \u043D\u0430 \u043F\u043E\u043A\u043E\u0439\u043D\u0438\u043A",
    url: "https://kiparisbg.com/prevoz-na-pokoinik",
    description: "\u0414\u0435\u043D\u043E\u043D\u043E\u0449\u0435\u043D \u043F\u0440\u0435\u0432\u043E\u0437 \u043D\u0430 \u043F\u043E\u043A\u043E\u0439\u043D\u0438\u043A \u0432 \u0441\u0442\u0440\u0430\u043D\u0430\u0442\u0430 \u0438 \u043C\u0435\u0436\u0434\u0443\u043D\u0430\u0440\u043E\u0434\u043D\u043E \u0440\u0435\u043F\u0430\u0442\u0440\u0438\u0440\u0430\u043D\u0435 \u043E\u0442/\u0434\u043E \u0411\u044A\u043B\u0433\u0430\u0440\u0438\u044F."
  },
  {
    slug: "nadgrobni-pametnici",
    name: "\u041D\u0430\u0434\u0433\u0440\u043E\u0431\u043D\u0438 \u043F\u0430\u043C\u0435\u0442\u043D\u0438\u0446\u0438",
    url: "https://kiparisbg.com/nadgrobni-pametnici",
    description: "\u0418\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0430 \u0438 \u043C\u043E\u043D\u0442\u0430\u0436 \u043D\u0430 \u043D\u0430\u0434\u0433\u0440\u043E\u0431\u043D\u0438 \u043F\u0430\u043C\u0435\u0442\u043D\u0438\u0446\u0438 \u043E\u0442 \u0433\u0440\u0430\u043D\u0438\u0442 \u0438 \u043C\u0440\u0430\u043C\u043E\u0440."
  },
  {
    slug: "traurni-stoki",
    name: "\u0422\u0440\u0430\u0443\u0440\u043D\u0438 \u0441\u0442\u043E\u043A\u0438",
    url: "https://kiparisbg.com/traurni-stoki",
    description: "\u041A\u043E\u0432\u0447\u0435\u0437\u0438, \u0432\u0435\u043D\u0446\u0438, \u043A\u0440\u044A\u0441\u0442\u043E\u0432\u0435 \u0438 \u0442\u0440\u0430\u0443\u0440\u043D\u0438 \u0430\u043A\u0441\u0435\u0441\u043E\u0430\u0440\u0438."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List funeral services",
  description: "List the funeral services offered by \u041A\u0438\u043F\u0430\u0440\u0438\u0441 2000 (\u043F\u043E\u0433\u0440\u0435\u0431\u0435\u043D\u0438\u0435, \u043A\u0440\u0435\u043C\u0430\u0446\u0438\u044F, \u0440\u0435\u043F\u0430\u0442\u0440\u0438\u0440\u0430\u043D\u0435, \u043F\u0430\u043C\u0435\u0442\u043D\u0438\u0446\u0438, \u0442\u0440\u0430\u0443\u0440\u043D\u0438 \u0441\u0442\u043E\u043A\u0438) with URLs and short descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CONTACT = {
  name: "\u0422\u0440\u0430\u0443\u0440\u043D\u0430 \u0430\u0433\u0435\u043D\u0446\u0438\u044F \u041A\u0438\u043F\u0430\u0440\u0438\u0441 2000",
  focus: "\u041C\u0435\u0436\u0434\u0443\u043D\u0430\u0440\u043E\u0434\u043D\u043E \u0440\u0435\u043F\u0430\u0442\u0440\u0438\u0440\u0430\u043D\u0435 \u0438 \u0434\u0435\u043D\u043E\u043D\u043E\u0449\u043D\u0438 \u0442\u0440\u0430\u0443\u0440\u043D\u0438 \u0443\u0441\u043B\u0443\u0433\u0438",
  phone: "02 846 55 24",
  phoneE164: "+35928465524",
  email: "kiparis2000@abv.bg",
  address: "1505 \u0421\u043E\u0444\u0438\u044F, \u0420\u0430\u0439\u043E\u043D \u041E\u0431\u043E\u0440\u0438\u0449\u0435, \u0443\u043B. \u201E\u041C\u044A\u0440\u0444\u0438\u201C \u2116 28, \u0411\u044A\u043B\u0433\u0430\u0440\u0438\u044F",
  hours: "\u0414\u0435\u043D\u043E\u043D\u043E\u0449\u043D\u043E, 7 \u0434\u043D\u0438 \u0432 \u0441\u0435\u0434\u043C\u0438\u0446\u0430\u0442\u0430",
  website: "https://kiparisbg.com",
  serviceAreas: [
    "\u0421\u043E\u0444\u0438\u044F \u0426\u0435\u043D\u0442\u044A\u0440",
    "\u0420\u0430\u0439\u043E\u043D \u041E\u0431\u043E\u0440\u0438\u0449\u0435",
    "\u041F\u043E\u0434\u0443\u044F\u043D\u0435",
    "\u0413\u0440\u043E\u0431\u0438\u0449\u0435\u043D \u043F\u0430\u0440\u043A \u041C\u0430\u043B\u0430\u0448\u0435\u0432\u0446\u0438",
    "\u0411\u0430\u043A\u044A\u0440\u0435\u043D\u0430 \u0444\u0430\u0431\u0440\u0438\u043A\u0430",
    "\u0426\u0435\u043D\u0442\u0440\u0430\u043B\u043D\u0438 \u0441\u043E\u0444\u0438\u0439\u0441\u043A\u0438 \u0433\u0440\u043E\u0431\u0438\u0449\u0430"
  ]
};
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact information",
  description: "Return contact details for \u0422\u0440\u0430\u0443\u0440\u043D\u0430 \u0430\u0433\u0435\u043D\u0446\u0438\u044F \u041A\u0438\u043F\u0430\u0440\u0438\u0441 2000: 24/7 phone line, email, Sofia address, and served districts/cemeteries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/convert-price.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var RATE = 1.95583;
var convert_price_default = defineTool3({
  name: "convert_price",
  title: "Convert BGN \u2194 EUR",
  description: "Convert a price between Bulgarian lev (BGN) and euro (EUR) using the fixed rate 1 EUR = 1.95583 BGN. Rounded to the nearest whole unit, matching how prices are displayed on the site.",
  inputSchema: {
    amount: z.number().positive().describe("Numeric amount to convert."),
    from: z.enum(["BGN", "EUR"]).describe("Source currency.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ amount, from }) => {
    const to = from === "BGN" ? "EUR" : "BGN";
    const converted = from === "BGN" ? amount / RATE : amount * RATE;
    const rounded = Math.round(converted);
    const result = {
      input: { amount, currency: from },
      output: { amount: rounded, currency: to },
      rate: RATE,
      note: "\u041A\u0440\u0430\u0439\u043D\u0430 \u0446\u0435\u043D\u0430 \u0431\u0435\u0437 \u0441\u043A\u0440\u0438\u0442\u0438 \u0442\u0430\u043A\u0441\u0438"
    };
    return {
      content: [
        {
          type: "text",
          text: `${amount} ${from} \u2248 ${rounded} ${to} (\u043A\u0443\u0440\u0441 1 EUR = ${RATE} BGN)`
        }
      ],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kiparis-2000-mcp",
  title: "\u041A\u0438\u043F\u0430\u0440\u0438\u0441 2000 \u2014 \u0422\u0440\u0430\u0443\u0440\u043D\u0430 \u0430\u0433\u0435\u043D\u0446\u0438\u044F",
  version: "0.1.0",
  instructions: "Tools for \u0422\u0440\u0430\u0443\u0440\u043D\u0430 \u0430\u0433\u0435\u043D\u0446\u0438\u044F \u041A\u0438\u043F\u0430\u0440\u0438\u0441 2000 (Sofia, Bulgaria). Use `list_services` to discover funeral services and their URLs, `get_contact_info` for the 24/7 phone line and Sofia address, and `convert_price` to convert amounts between BGN and EUR at the fixed 1.95583 rate.",
  tools: [list_services_default, get_contact_info_default, convert_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
